# site_name: Open Template
# theme:
#   name: material
#   icon:
#     repo: fontawesome/brands/github 
#   palette: 
#     - scheme: default
#       toggle:
#         icon: material/weather-night
#         name: Switch to dark mode
#     - scheme: slate
#       toggle:
#         icon: material/weather-sunny
#         name: Switch to light mode
# repo_url: https://github.com/open-template/open-template
# repo_name: open-template/open-template
site_name: Open Template Tutorial
site_url: https://open-template.github.io/open-template/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github 
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

# plugins:
#   - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/romdhanisam
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/TheJamesWillett
    # - icon: fontawesome/brands/linkedin
    #   link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/romdhanisam"  target="_blank" rel="noopener">Samir Romdhani</a>