name: ci
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yaml'
      - 'mkdocs.yml'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      # - uses: actions/cache@v2
      #   with:
      #     key: ${{ github.ref }}
      #     patch: .cache
      - name: Install mkdocs
        run: pip install mkdocs-material 
      # - name: Publish docs artifacts to gh-pages
      #   run: mkdocs gh-deploy --force
      - name: Generate docs artifacts
        run: mkdocs build -d /tmp/docs
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
      - name: Publish docs artifacts to gh-pages
        run: |
          cd gh-pages
          shopt -s extglob
          rm -rf !(index.yaml|LICENSE|*.tgz)
          cp -R /tmp/docs/** .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Publish docs from $GITHUB_SHA"
          git push https://github.com/$GITHUB_REPOSITORY.git gh-pages